on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Build project
        env: 
          VITE_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          VITE_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          VITE_AWS_REGION: "ap-south-1"
          VITE_S3_BUCKET_NAME: "assets.manastik.com"
        run: npm run build
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist
      - name: Deploy to AWS S3 DEV
        if: ${{ github.event.label.name == 'dev-deploy' }}
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: ./dist/
          destination: s3://adminportaldev.manastik.com/
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-south-1
          flags: --recursive
      - name: Deploy to AWS S3 TEST
        if: ${{ github.event.label.name == 'test-deploy' }}
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: ./dist/
          destination: s3://adminportaltest.manastik.com/
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-south-1
          flags: --recursive
